-- Bundled sample bank data from Dirt-Samples
-- Auto-generated by scripts/update_sample_data.lua
-- Descriptions from https://github.com/tedthetrumpet/tidal/blob/master/allthesamples.tidal
-- File listings from https://github.com/tidalcycles/Dirt-Samples

local M = {}

M.banks = {
  ["808"] = {
    description = "6 misc 808 sound",
    files = {
    "CB.WAV",
    "CH.WAV",
    "CL.WAV",
    "CP.WAV",
    "MA.WAV",
    "RS.WAV"
  },
  },
  ["808bd"] = {
    description = "25 rather similar 808 kicks!",
    files = {
    "BD0000.WAV",
    "BD0010.WAV",
    "BD0025.WAV",
    "BD0050.WAV",
    "BD0075.WAV",
    "BD1000.WAV",
    "BD1010.WAV",
    "BD1025.WAV",
    "BD1050.WAV",
    "BD1075.WAV",
    "BD2500.WAV",
    "BD2510.WAV",
    "BD2525.WAV",
    "BD2550.WAV",
    "BD2575.WAV",
    "BD5000.WAV",
    "BD5010.WAV",
    "BD5025.WAV",
    "BD5050.WAV",
    "BD5075.WAV",
    "BD7500.WAV",
    "BD7510.WAV",
    "BD7525.WAV",
    "BD7550.WAV",
    "BD7575.WAV"
  },
  },
  ["808cy"] = {
    description = "25 808 cymbals",
    files = {
    "CY0000.WAV",
    "CY0010.WAV",
    "CY0025.WAV",
    "CY0050.WAV",
    "CY0075.WAV",
    "CY1000.WAV",
    "CY1010.WAV",
    "CY1025.WAV",
    "CY1050.WAV",
    "CY1075.WAV",
    "CY2500.WAV",
    "CY2510.WAV",
    "CY2525.WAV",
    "CY2550.WAV",
    "CY2575.WAV",
    "CY5000.WAV",
    "CY5010.WAV",
    "CY5025.WAV",
    "CY5050.WAV",
    "CY5075.WAV",
    "CY7500.WAV",
    "CY7510.WAV",
    "CY7525.WAV",
    "CY7550.WAV",
    "CY7575.WAV"
  },
  },
  ["808hc"] = {
    description = "5 808 high congas",
    files = {
    "HC00.WAV",
    "HC10.WAV",
    "HC25.WAV",
    "HC50.WAV",
    "HC75.WAV"
  },
  },
  ["808ht"] = {
    description = "5 808 high toms, bit noisy",
    files = {
    "HT00.WAV",
    "HT10.WAV",
    "HT25.WAV",
    "HT50.WAV",
    "HT75.WAV"
  },
  },
  ["808lc"] = {
    description = "5 808 low congas, noisy",
    files = {
    "LC00.WAV",
    "LC10.WAV",
    "LC25.WAV",
    "LC50.WAV",
    "LC75.WAV"
  },
  },
  ["808lt"] = {
    description = "5 808 low toms, noisy",
    files = {
    "LT00.WAV",
    "LT10.WAV",
    "LT25.WAV",
    "LT50.WAV",
    "LT75.WAV"
  },
  },
  ["808mc"] = {
    description = "5 808 medium congas",
    files = {
    "MC00.WAV",
    "MC10.WAV",
    "MC25.WAV",
    "MC50.WAV",
    "MC75.WAV"
  },
  },
  ["808mt"] = {
    description = "",
    files = {
    "MT00.WAV",
    "MT10.WAV",
    "MT25.WAV",
    "MT50.WAV",
    "MT75.WAV"
  },
  },
  ["808oh"] = {
    description = "5 808 open hats",
    files = {
    "OH00.WAV",
    "OH10.WAV",
    "OH25.WAV",
    "OH50.WAV",
    "OH75.WAV"
  },
  },
  ["808sd"] = {
    description = "25 808 snares",
    files = {
    "SD0000.WAV",
    "SD0010.WAV",
    "SD0025.WAV",
    "SD0050.WAV",
    "SD0075.WAV",
    "SD1000.WAV",
    "SD1010.WAV",
    "SD1025.WAV",
    "SD1050.WAV",
    "SD1075.WAV",
    "SD2500.WAV",
    "SD2510.WAV",
    "SD2525.WAV",
    "SD2550.WAV",
    "SD2575.WAV",
    "SD5000.WAV",
    "SD5010.WAV",
    "SD5025.WAV",
    "SD5050.WAV",
    "SD5075.WAV",
    "SD7500.WAV",
    "SD7510.WAV",
    "SD7525.WAV",
    "SD7550.WAV",
    "SD7575.WAV"
  },
  },
  ["909"] = {
    description = "just one 909 kick, but very nice",
    files = {
    "BT0A0A7.WAV"
  },
  },
  ["ab"] = {
    description = "nice subtle drum sounds",
    files = {
    "000_ab2closedhh.wav",
    "001_ab2crash.wav",
    "002_ab2hit1.wav",
    "003_ab2hit2.wav",
    "004_ab2kick1.wav",
    "005_ab2kick2.wav",
    "006_ab2openhh.wav",
    "007_ab2perc1.wav",
    "008_ab2perc2.wav",
    "009_ab2ride.wav",
    "010_ab2snare1.wav",
    "011_ab2snare2.wav"
  },
  },
  ["ade"] = {
    description = "various long samples",
    files = {
    "000_011112-bassline.wav",
    "001_011112-melody.wav",
    "002_20020506-01.wav",
    "003_abt.wav",
    "004_fan.wav",
    "005_fanbass.wav",
    "006_glass.wav",
    "007_microsound.wav",
    "008_rhythm.wav",
    "009_rise.wav"
  },
  },
  ["ades2"] = {
    description = "meh, short quiet noisy sounds",
    files = {
    "000_01.wav",
    "001_02.wav",
    "002_03.wav",
    "003_04.wav",
    "004_05.wav",
    "005_06.wav",
    "006_07.wav",
    "007_08.wav",
    "008_09.wav"
  },
  },
  ["ades3"] = {
    description = "short noisy sounds, lowish pitch",
    files = {
    "01.wav",
    "02.wav",
    "03.wav",
    "04.wav",
    "05.wav",
    "06.wav",
    "07.wav"
  },
  },
  ["ades4"] = {
    description = "short high pitched sounds",
    files = {
    "01.wav",
    "02.wav",
    "03.wav",
    "04.wav",
    "05.wav",
    "06.wav"
  },
  },
  ["alex"] = {
    description = "two acoustic drum loops",
    files = {
    "000_drumx1.wav",
    "001_drumx2.wav"
  },
  },
  ["alphabet"] = {
    description = "tts",
    files = {
    "a.wav",
    "b.wav",
    "c.wav",
    "d.wav",
    "e.wav",
    "f.wav",
    "g.wav",
    "h.wav",
    "i.wav",
    "j.wav",
    "k.wav",
    "l.wav",
    "m.wav",
    "n.wav",
    "o.wav",
    "p.wav",
    "q.wav",
    "r.wav",
    "s.wav",
    "t.wav",
    "u.wav",
    "v.wav",
    "w.wav",
    "x.wav",
    "y.wav",
    "z.wav"
  },
  },
  ["amencutup"] = {
    description = "wisott",
    files = {
    "000_AMENCUT_001.wav",
    "001_AMENCUT_002.wav",
    "002_AMENCUT_003.wav",
    "003_AMENCUT_004.wav",
    "004_AMENCUT_005.wav",
    "005_AMENCUT_006.wav",
    "006_AMENCUT_007.wav",
    "007_AMENCUT_008.wav",
    "008_AMENCUT_009.wav",
    "009_AMENCUT_010.wav",
    "010_AMENCUT_011.wav",
    "011_AMENCUT_012.wav",
    "012_AMENCUT_013.wav",
    "013_AMENCUT_014.wav",
    "014_AMENCUT_015.wav",
    "015_AMENCUT_016.wav",
    "016_AMENCUT_017.wav",
    "017_AMENCUT_018.wav",
    "018_AMENCUT_019.wav",
    "019_AMENCUT_020.wav",
    "020_AMENCUT_021.wav",
    "021_AMENCUT_022.wav",
    "022_AMENCUT_023.wav",
    "023_AMENCUT_024.wav",
    "024_AMENCUT_025.wav",
    "025_AMENCUT_026.wav",
    "026_AMENCUT_027.wav",
    "027_AMENCUT_028.wav",
    "028_AMENCUT_029.wav",
    "029_AMENCUT_030.wav",
    "030_AMENCUT_031.wav",
    "031_AMENCUT_032.wav"
  },
  },
  ["armora"] = {
    description = "probably useless low pitched noise",
    files = {
    "000_beep.wav",
    "001_chopper.wav",
    "002_hiexp.wav",
    "003_jeepfire.wav",
    "004_loexp.wav",
    "005_tankeng.wav",
    "006_tankfire.wav"
  },
  },
  ["arp"] = {
    description = "two synth notes, low and high, both c#?!?",
    files = {
    "000_arp2.wav",
    "001_arp.wav"
  },
  },
  ["arpy"] = {
    description = "as below",
    files = {
    "arpy01.wav",
    "arpy02.wav",
    "arpy03.wav",
    "arpy04.wav",
    "arpy05.wav",
    "arpy06.wav",
    "arpy07.wav",
    "arpy08.wav",
    "arpy09.wav",
    "arpy10.wav",
    "arpy11.wav"
  },
  },
  ["auto"] = {
    description = "various effected drum sounds",
    files = {
    "000_break-kick.wav",
    "001_break-ride.wav",
    "002_break-sd.wav",
    "003_cymrev.wav",
    "004_kick.wav",
    "005_kick-ambient.wav",
    "006_sd.wav",
    "007_sd-ambient.wav",
    "008_shake1.wav",
    "009_shake2.wav",
    "010_shake3.wav"
  },
  },
  ["baa"] = {
    description = "sheep sounds, why?!?",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav",
    "7.wav"
  },
  },
  ["baa2"] = {
    description = "rather simlar to the above? same?",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav",
    "7.wav"
  },
  },
  ["bass"] = {
    description = "four short bass sounds, nasty abrupt release",
    files = {
    "000_bass1.wav",
    "001_bass2.wav",
    "002_bass3.wav",
    "003_bass4.wav"
  },
  },
  ["bass0"] = {
    description = "one highly distorted bass drum, plus?!?!?",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav"
  },
  },
  ["bass1"] = {
    description = "thirty synth bass sounds, some long, f or c",
    files = {
    "18076__daven__01-sb-bass-hit-c.wav",
    "18077__daven__02-sb-bass-hit-c.wav",
    "18078__daven__03-sb-bass-hit-c.wav",
    "18079__daven__04-sb-bass-hit-c.wav",
    "18080__daven__05-sb-bass-hit-c.wav",
    "18081__daven__06-sb-bass-hit-c.wav",
    "18082__daven__07-sb-bass-hit-c.wav",
    "18083__daven__08-sb-bass-hit-c.wav",
    "18084__daven__09-sb-bass-hit-c.wav",
    "18085__daven__10-sb-bass-hit-c.wav",
    "18086__daven__11-sb-bass-hit-c.wav",
    "18087__daven__12-sb-bass-hit-c.wav",
    "18088__daven__13-sb-bass-hit-c.wav",
    "18089__daven__14-sb-bass-hit-c.wav",
    "18090__daven__15-sb-bass-hit-c.wav",
    "18091__daven__16-sb-bass-hit-c.wav",
    "18092__daven__17-sb-bass-hit-c.wav",
    "18093__daven__18-sb-bass-hit-c.wav",
    "18094__daven__19-sb-bass-hit-f.wav",
    "18095__daven__20-sb-bass-hit-f.wav",
    "18096__daven__21-sb-bass-hit-f.wav",
    "18097__daven__22-sb-bass-hit-f.wav",
    "18098__daven__23-sb-bass-hit-f.wav",
    "18099__daven__24-sb-bass-hit-f.wav",
    "18100__daven__25-sb-bass-hit-f.wav",
    "18101__daven__26-sb-bass-hit-f.wav",
    "18102__daven__27-sb-bass-hit-f.wav",
    "18103__daven__28-sb-bass-hit-f.wav",
    "18104__daven__29-sb-bass-hit-f.wav",
    "18105__daven__30-sb-bass-hit-f.wav"
  },
  },
  ["bass2"] = {
    description = "five aggressive tonal kicks",
    files = {
    "69988__noizemassacre__hardcore-bass-1.wav",
    "69989__noizemassacre__hardcore-bass-2.wav",
    "69990__noizemassacre__hardcore-bass-3.wav",
    "69991__noizemassacre__hardcore-bass-4.wav",
    "69992__noizemassacre__hardcore-bass-5.wav"
  },
  },
  ["bass3"] = {
    description = "eleven bass sounds, odd mix of pitches",
    files = {
    "83245__zgump__bass-0201.wav",
    "83246__zgump__bass-0202.wav",
    "83247__zgump__bass-0203.wav",
    "83248__zgump__bass-0204.wav",
    "83249__zgump__bass-0205.wav",
    "83250__zgump__bass-0206.wav",
    "83251__zgump__bass-0207.wav",
    "83252__zgump__bass-0208.wav",
    "83253__zgump__bass-0209.wav",
    "85056__zgump__reverse-bass-01.wav",
    "85057__zgump__reverse-bass-02.wav"
  },
  },
  ["bassdm"] = {
    description = "24 rather similar acoustic-ish kicks",
    files = {
    "001_BT0A0A7.WAV",
    "002_BT0A0D0.WAV",
    "003_BT0A0D3.WAV",
    "004_BT0A0DA.WAV",
    "005_BT0AAD0.WAV",
    "006_BT0AADA.WAV",
    "007_BT3A0D0.WAV",
    "008_BT3A0D3.WAV",
    "009_BT3A0D7.WAV",
    "010_BT3A0DA.WAV",
    "011_BT3AAD0.WAV",
    "012_BT3AADA.WAV",
    "013_BT7A0D0.WAV",
    "014_BT7A0D3.WAV",
    "015_BT7A0D7.WAV",
    "016_BT7A0DA.WAV",
    "017_BT7AAD0.WAV",
    "018_BT7AADA.WAV",
    "019_BTAA0D0.WAV",
    "020_BTAA0D3.WAV",
    "021_BTAA0D7.WAV",
    "022_BTAA0DA.WAV",
    "023_BTAAAD0.WAV",
    "024_BTAAADA.WAV"
  },
  },
  ["bassfoo"] = {
    description = "same bank as bass0",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav"
  },
  },
  ["battles"] = {
    description = "very reverb military snare, hit and roll",
    files = {
    "000_explo1.wav",
    "001_explo2.wav"
  },
  },
  ["bd"] = {
    description = "lots of electo kicks, mostly quite similar",
    files = {
    "BT0A0A7.wav",
    "BT0A0D0.wav",
    "BT0A0D3.wav",
    "BT0A0DA.wav",
    "BT0AAD0.wav",
    "BT0AADA.wav",
    "BT3A0D0.wav",
    "BT3A0D3.wav",
    "BT3A0D7.wav",
    "BT3A0DA.wav",
    "BT3AAD0.wav",
    "BT3AADA.wav",
    "BT7A0D0.wav",
    "BT7A0D3.wav",
    "BT7A0D7.wav",
    "BT7A0DA.wav",
    "BT7AAD0.wav",
    "BT7AADA.wav",
    "BTAA0D0.wav",
    "BTAA0D3.wav",
    "BTAA0D7.wav",
    "BTAA0DA.wav",
    "BTAAAD0.wav",
    "BTAAADA.wav"
  },
  },
  ["bend"] = {
    description = "four subtle noisy sounds",
    files = {
    "000_2.wav",
    "001_5.wav",
    "002_6.wav",
    "003_8.wav"
  },
  },
  ["bev"] = {
    description = "eight bar vocal keyboard/bass loop (mono)",
    files = {
    "00-mono.wav",
    "01-stereo.wav"
  },
  },
  ["bin"] = {
    description = "yup, two dustbin hits, kind of ok, could be a snare",
    files = {
    "000_bin1.wav",
    "001_0.wav"
  },
  },
  ["birds"] = {
    description = "chaffinches, nightingales etc",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_2.wav",
    "003_3.wav",
    "004_4.wav",
    "005_5.wav",
    "006_6.wav",
    "007_7.wav",
    "008_8.wav",
    "009_9.wav"
  },
  },
  ["birds3"] = {
    description = "very short noisy sounds, highish pitch",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_11.wav",
    "003_12.wav",
    "004_13.wav",
    "005_14.wav",
    "006_15.wav",
    "007_16.wav",
    "008_17.wav",
    "009_18.wav",
    "010_19.wav",
    "011_2.wav",
    "012_3.wav",
    "013_4.wav",
    "014_5.wav",
    "015_6.wav",
    "016_7.wav",
    "017_8.wav",
    "018_9.wav"
  },
  },
  ["bleep"] = {
    description = "rtd2 ish, loud!",
    files = {
    "boip.wav",
    "checkpoint-hit.wav",
    "echo-blip-thing.wav",
    "harsh-whippleszoot.wav",
    "pc_beep.wav",
    "shortsaxish.wav",
    "simpletone.wav",
    "stereo-star-trek-pager.wav",
    "tiniest.wav",
    "tinynote.wav",
    "vidgame-bleep1.wav",
    "vidgame-bleep2.wav",
    "watch_beep.wav"
  },
  },
  ["blip"] = {
    description = "two short pitched sounds, minor seventh apart",
    files = {
    "000_blipp01.wav",
    "001_blipp02.wav"
  },
  },
  ["blue"] = {
    description = "two spoken fragments, unintelligible",
    files = {
    "aya.wav",
    "howdoesitfeel.wav"
  },
  },
  ["bottle"] = {
    description = "short sounds, might be a bottle",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_11.wav",
    "003_12.wav",
    "004_13.wav",
    "005_2.wav",
    "006_3.wav",
    "007_4.wav",
    "008_5.wav",
    "009_6.wav",
    "010_7.wav",
    "011_8.wav",
    "012_9.wav"
  },
  },
  ["breaks125"] = {
    description = "two one-bar breakbeats",
    files = {
    "015_sdstckbr.wav",
    "016_bllstmp.wav"
  },
  },
  ["breaks152"] = {
    description = "one bar of amen at 152",
    files = {
    "000_AMEN.WAV"
  },
  },
  ["breaks157"] = {
    description = "one bar break at 157",
    files = {
    "000_PLEAD.WAV"
  },
  },
  ["breaks165"] = {
    description = "one bar amen at 165",
    files = {
    "000_RAWCLN.WAV"
  },
  },
  ["breath"] = {
    description = "one breath sound, pretty pointless",
    files = {
    "000_breath.wav"
  },
  },
  ["bubble"] = {
    description = "actually sound more or less like kicks",
    files = {
    "000_bub0.wav",
    "001_bub1.wav",
    "002_bub2.wav",
    "003_bub3.wav",
    "004_bub4.wav",
    "005_bub5.wav",
    "006_bub6.wav",
    "007_bub7.wav"
  },
  },
  ["can"] = {
    description = "intersting percussive sounds",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_11.wav",
    "003_12.wav",
    "004_13.wav",
    "005_14.wav",
    "006_2.wav",
    "007_3.wav",
    "008_4.wav",
    "009_5.wav",
    "010_6.wav",
    "011_7.wav",
    "012_8.wav",
    "013_9.wav"
  },
  },
  ["casio"] = {
    description = "just three cheapo 'drum' sounds",
    files = {
    "high.wav",
    "low.wav",
    "noise.wav"
  },
  },
  ["cb"] = {
    description = "omg what is that sound, so familiar! iya -- nearly same as 808:0",
    files = {
    "rytm-cb.wav"
  },
  },
  ["cc"] = {
    description = "some loud reverby cymbals",
    files = {
    "CSHD0.wav",
    "CSHD2.wav",
    "CSHD4.wav",
    "CSHD6.wav",
    "CSHD8.wav",
    "CSHDA.wav"
  },
  },
  ["chin"] = {
    description = "very quiet synthetic clicks",
    files = {
    "000_tik1.wav",
    "001_tik2.wav",
    "002_tik3.wav",
    "003_tik4.wav"
  },
  },
  ["circus"] = {
    description = "three strange and pointless sounds",
    files = {
    "000_bounce.wav",
    "001_miss.wav",
    "002_pop.wav"
  },
  },
  ["clak"] = {
    description = "two quiet typewriters clicks, or clock ticks?",
    files = {
    "000_clak1.wav",
    "001_clak2.wav"
  },
  },
  ["click"] = {
    description = "four glitch sounds, maybe useful",
    files = {
    "000_click0.wav",
    "001_click1.wav",
    "002_click2.wav",
    "003_click3.wav"
  },
  },
  ["clubkick"] = {
    description = "five similar very aggressive kicks",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav"
  },
  },
  ["co"] = {
    description = "various hats",
    files = {
    "CLOP1.wav",
    "CLOP2.wav",
    "CLOP3.wav",
    "CLOP4.wav"
  },
  },
  ["coins"] = {
    description = "very quiet coin chink",
    files = {
    "coins.wav"
  },
  },
  ["control"] = {
    description = "two synth notes, out of tune",
    files = {
    "1.wav",
    "2.wav"
  },
  },
  ["cosmicg"] = {
    description = "strange mix of bleeps and loud noise",
    files = {
    "000_cg_att.wav",
    "001_cg_chnc.wav",
    "002_cg_dest.wav",
    "003_cg_ext.wav",
    "004_cg_gotb.wav",
    "005_cg_gotm.wav",
    "006_cg_gun.wav",
    "007_cg_m0.wav",
    "008_cg_m1.wav",
    "009_cg_m2.wav",
    "010_cg_m3.wav",
    "011_cg_m4.wav",
    "012_cg_m5.wav",
    "013_cg_m6.wav",
    "014_cg_m7.wav"
  },
  },
  ["cp"] = {
    description = "two rather similar claps",
    files = {
    "HANDCLP0.wav",
    "HANDCLPA.wav"
  },
  },
  ["cr"] = {
    description = "six ride cymbs",
    files = {
    "RIDED0.wav",
    "RIDED2.wav",
    "RIDED4.wav",
    "RIDED6.wav",
    "RIDED8.wav",
    "RIDEDA.wav"
  },
  },
  ["crow"] = {
    description = "two crow sounds twice",
    files = {
    "000_crow.wav",
    "001_crow2.wav",
    "002_crow3.wav",
    "003_crow4.wav"
  },
  },
  ["d"] = {
    description = "four misc useless sounds",
    files = {
    "000_d1.wav",
    "001_d2.wav",
    "002_d3.wav",
    "003_d4.wav"
  },
  },
  ["db"] = {
    description = "hmm, pretty usable dry drumkit iya",
    files = {
    "dbs12closedhh.wav",
    "dbs12crash.wav",
    "dbs12hit1.wav",
    "dbs12hit2.wav",
    "dbs12hit3.wav",
    "dbs12kick1.wav",
    "dbs12kick2.wav",
    "dbs12openhh.wav",
    "dbs12perc1.wav",
    "dbs12perc2.wav",
    "dbs12ride.wav",
    "dbs12snare1.wav",
    "dbs12snare2.wav"
  },
  },
  ["diphone"] = {
    description = "tts",
    files = {
    "000_kd1_002.wav",
    "001_kd1_003.wav",
    "002_kd1_004.wav",
    "003_kd1_005.wav",
    "004_kd1_006.wav",
    "005_kd1_007.wav",
    "006_kd1_008.wav",
    "007_kd1_009.wav",
    "008_kd1_010.wav",
    "009_kd1_011.wav",
    "010_kd1_012.wav",
    "011_kd1_013.wav",
    "012_kd1_014.wav",
    "013_kd1_015.wav",
    "014_kd1_016.wav",
    "015_kd1_017.wav",
    "016_kd1_018.wav",
    "017_kd1_019.wav",
    "018_kd1_020.wav",
    "019_kd1_021.wav",
    "020_kd1_022.wav",
    "021_kd1_023.wav",
    "022_kd1_024.wav",
    "023_kd1_025.wav",
    "024_kd1_026.wav",
    "025_kd1_027.wav",
    "026_kd1_028.wav",
    "027_kd1_029.wav",
    "028_kd1_030.wav",
    "029_kd1_031.wav",
    "030_kd1_032.wav",
    "031_kd1_033.wav",
    "032_kd1_034.wav",
    "033_kd1_035.wav",
    "034_kd1_036.wav",
    "035_kd1_037.wav",
    "036_kd1_038.wav",
    "037_kd1_039.wav"
  },
  },
  ["diphone2"] = {
    description = "tts",
    files = {
    "000_kd1_399.wav",
    "001_kd1_400.wav",
    "002_kd1_401.wav",
    "003_kd1_402.wav",
    "004_kd1_403.wav",
    "005_kd1_404.wav",
    "006_kd1_405.wav",
    "007_kd1_406.wav",
    "008_kd3_010.wav",
    "009_kd3_011.wav",
    "010_kd3_012.wav",
    "011_kd3_013.wav"
  },
  },
  ["dist"] = {
    description = "16 highly distorted 1 bar drum loops",
    files = {
    "000_inddistb1.wav",
    "001_inddistb2.wav",
    "002_inddistb1ride.wav",
    "003_inddistb2ride.wav",
    "004_inddistb3.wav",
    "005_inddistb3ride.wav",
    "006_inddistb4.wav",
    "007_inddistb4ride.wav",
    "008_inddistb5.wav",
    "009_inddistb5ride.wav",
    "010_inddistb6.wav",
    "011_inddistb6ride.wav",
    "012_inddistb7.wav",
    "013_inddistb7ride.wav",
    "014_inddistb8.wav",
    "015_inddistb8ride.wav"
  },
  },
  ["dork2"] = {
    description = "four sounds, nae idea, voices in a space?",
    files = {
    "0.wav",
    "1.wav",
    "2.wav",
    "4.wav"
  },
  },
  ["dorkbot"] = {
    description = "people saying dorkbot, two variations",
    files = {
    "1.wav",
    "2.wav"
  },
  },
  ["dr"] = {
    description = "loud midi drumkit, nasty cutoff at end",
    files = {
    "000_002.WAV",
    "001_003.WAV",
    "002_004.WAV",
    "003_005.WAV",
    "004_006.WAV",
    "005_008.WAV",
    "006_009.WAV",
    "007_010.WAV",
    "008_011.WAV",
    "009_014.WAV",
    "010_015.WAV",
    "011_016.WAV",
    "012_017.WAV",
    "013_019.WAV",
    "014_023.WAV",
    "015_024.WAV",
    "016_025.WAV",
    "017_026.WAV",
    "018_027.WAV",
    "019_028.WAV",
    "020_029.WAV",
    "021_030.WAV",
    "022_031.WAV",
    "023_032.WAV",
    "024_033.WAV",
    "025_034.WAV",
    "026_035.WAV",
    "027_036.WAV",
    "028_037.WAV",
    "029_038.WAV",
    "030_039.WAV",
    "031_040.WAV",
    "032_041.WAV",
    "033_042.WAV",
    "034_043.WAV",
    "035_044.WAV",
    "036_045.WAV",
    "037_046.WAV",
    "038_047.WAV",
    "039_048.WAV",
    "040_049.WAV",
    "041_050.WAV"
  },
  },
  ["dr2"] = {
    description = "six clean electro drum sounds",
    files = {
    "000_DR110CHT.WAV",
    "001_DR110CLP.WAV",
    "002_DR110CYM.WAV",
    "003_DR110KIK.WAV",
    "004_DR110OHT.WAV",
    "005_DR110SNR.WAV"
  },
  },
  ["dr55"] = {
    description = "four dr55 sounds",
    files = {
    "000_DR55 hi hat.wav",
    "001_DR55 kick.wav",
    "002_DR55 rimshot.wav",
    "003_DR55 snare.wav"
  },
  },
  ["dr_few"] = {
    description = "eight loud drum sounds",
    files = {
    "000_001.WAV",
    "001_007.WAV",
    "002_012.WAV",
    "003_013.WAV",
    "004_018.WAV",
    "005_020.WAV",
    "006_021.WAV",
    "007_022.WAV"
  },
  },
  ["drum"] = {
    description = "",
    files = {
    "000_drum1.wav",
    "001_drum2.wav",
    "002_drum3.wav",
    "003_drum4.wav",
    "004_drum5.wav",
    "005_drum6.wav"
  },
  },
  ["drumtraks"] = {
    description = "loudish kit",
    files = {
    "000_DT Cabasa.wav",
    "001_DT Claps.wav",
    "002_DT Cowbell.wav",
    "003_DT Crash.wav",
    "004_DT Hat Closed.wav",
    "005_DT Hat Open.wav",
    "006_DT Kick.wav",
    "007_DT Ride.wav",
    "008_DT Rimshot.wav",
    "009_DT Snare.wav",
    "010_DT Tambourine.wav",
    "011_DT Tom1.wav",
    "012_DT Tom2.wav"
  },
  },
  ["e"] = {
    description = "8 short and quiet glitchy sounds, similar",
    files = {
    "000_e1.wav",
    "001_e2.wav",
    "002_e3.wav",
    "003_e4.wav",
    "004_e5.wav",
    "005_e6.wav",
    "006_e7.wav",
    "007_e8.wav"
  },
  },
  ["east"] = {
    description = "9 'world' drum sounds, ok",
    files = {
    "000_nipon_wood_block.wav",
    "001_ohkawa_mute.wav",
    "002_ohkawa_open.wav",
    "003_shime_hi.wav",
    "004_shime_hi_2.wav",
    "005_shime_mute.wav",
    "006_taiko_1.wav",
    "007_taiko_2.wav",
    "008_taiko_3.wav"
  },
  },
  ["electro1"] = {
    description = "",
    files = {
    "000_et1closedhh.wav",
    "001_et1crash.wav",
    "002_et1hit1.wav",
    "003_et1hit2.wav",
    "004_et1hit3.wav",
    "005_et1kick1.wav",
    "006_et1kick2.wav",
    "007_et1openhh.wav",
    "008_et1perc1.wav",
    "009_et1perc2.wav",
    "010_et1ride.wav",
    "011_et1snare1.wav",
    "012_et1snare2.wav"
  },
  },
  ["em2"] = {
    description = "six longer sounds, kalimba, flute, loon?",
    files = {
    "0.wav",
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav"
  },
  },
  ["erk"] = {
    description = "voice 'one two three hit it'",
    files = {
    "000_123.wav"
  },
  },
  ["f"] = {
    description = "one short synth note, actually a bit below Eb",
    files = {
    "000_f.wav"
  },
  },
  ["feel"] = {
    description = "quite nice bank of 7 drum sounds",
    files = {
    "BD 04 d.wav",
    "HH 003b.wav",
    "Sd 139.wav",
    "Sd 180.wav",
    "Sd 223.wav",
    "hihat029a.wav",
    "sub.wav"
  },
  },
  ["feelfx"] = {
    description = "varied effected sounds, bit longer, ok",
    files = {
    "blnk.wav",
    "boschwitz.wav",
    "bwawp.wav",
    "doing.wav",
    "laser-buzz.wav",
    "machine.wav",
    "silent.wav",
    "surfactant_15_xilo.wav"
  },
  },
  ["fest"] = {
    description = "voice saying 'bling?' or 'berlin?'",
    files = {
    "000_foo.wav"
  },
  },
  ["fire"] = {
    description = "longish sample of fire sounds, low ambience",
    files = {
    "fire.wav"
  },
  },
  ["flick"] = {
    description = "mix of 17 hits couple of long Cs",
    files = {
    "000_square-p.wav",
    "001_1.wav",
    "002_10.wav",
    "003_11.wav",
    "004_12.wav",
    "005_13.wav",
    "006_14.wav",
    "007_2.wav",
    "008_3.wav",
    "009_4.wav",
    "010_5.wav",
    "011_6.wav",
    "012_7.wav",
    "013_8.wav",
    "014_9.wav",
    "015_hi.wav",
    "016_square.wav"
  },
  },
  ["fm"] = {
    description = "whole bank of loops! inc '31 seconds…'",
    files = {
    "31seconds.wav",
    "808909stabs.wav",
    "badboy.wav",
    "bambaataa.wav",
    "break1.wav",
    "break2.wav",
    "break3.wav",
    "charly.wav",
    "electro1.wav",
    "electro2.wav",
    "femalevocal1.wav",
    "femalevocal2.wav",
    "femalevocal3.wav",
    "heyhey.wav",
    "pad.wav",
    "shakedown.wav",
    "stabs.wav"
  },
  },
  ["foo"] = {
    description = "every breakbeat evah",
    files = {
    "000_samthfdbrk.wav",
    "001_frtwbrak.wav",
    "002_fullbrk.wav",
    "003_drydrmmr.wav",
    "004_brtalhat.wav",
    "005_nicedrop.wav",
    "006_fastfaze.wav",
    "007_lkfnkybr.wav",
    "008_clnkrbrk.wav",
    "009_hrdlvbrk.wav",
    "010_dngrsbrk.wav",
    "011_eyebreak.wav",
    "012_vctrybrk.wav",
    "013_mrestick.wav",
    "014_thumpnbr.wav",
    "015_sdstckbr.wav",
    "016_bllstmp.wav",
    "017_gattabrk.wav",
    "018_nlzdelit.wav",
    "019_crshstmp.wav",
    "020_fststick.wav",
    "021_sqezdbrk.wav",
    "022_cnfssbrk.wav",
    "023_btstmpbr.wav",
    "024_rlltnbrk.wav",
    "025_pssbreak.wav",
    "026_vintage.wav"
  },
  },
  ["future"] = {
    description = "synthetic hits, mostly kicks",
    files = {
    "000_808KICK4.wav",
    "001_808KICK9.wav",
    "002_Bd1_w.wav",
    "003_Bd2_w.wav",
    "004_Bd3_w.wav",
    "005_Johnson.wav",
    "006_Kick9.wav",
    "007_MKD03.wav",
    "008_MKD60601.wav",
    "009_MKDRCK05.wav",
    "010_MKDRCK06.wav",
    "011_MKDRCK07.wav",
    "012_Mhhcf3.wav",
    "013_Shake2.wav",
    "014_Shake4.wav",
    "015_lockett_conga_mute2.wav",
    "016_lockett_conga_open1.wav"
  },
  },
  ["gab"] = {
    description = "bitcrushed hits",
    files = {
    "gab01.wav",
    "gab02.wav",
    "gab03.wav",
    "gab04.wav",
    "gab05.wav",
    "gab06.wav",
    "gab07.wav",
    "gab08.wav",
    "gab09.wav",
    "gab10.wav"
  },
  },
  ["gabba"] = {
    description = "bitcrushed kit, four sounds",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav"
  },
  },
  ["gabbaloud"] = {
    description = "wisott",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav"
  },
  },
  ["gabbalouder"] = {
    description = "wisott",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav"
  },
  },
  ["glasstap"] = {
    description = "three nondescript short dry sounds",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav"
  },
  },
  ["glitch"] = {
    description = "iya Eb/Ab stab at 5",
    files = {
    "000_BD.wav",
    "001_CB.wav",
    "002_FX.wav",
    "003_HH.wav",
    "004_OH.wav",
    "005_P1.wav",
    "006_P2.wav",
    "007_SN.wav"
  },
  },
  ["glitch2"] = {
    description = "same?!?",
    files = {
    "000_BD.wav",
    "001_CB.wav",
    "002_FX.wav",
    "003_HH.wav",
    "004_OH.wav",
    "005_P1.wav",
    "006_P2.wav",
    "007_SN.wav"
  },
  },
  ["gretsch"] = {
    description = "acoustic kit, inc flams",
    files = {
    "000_brushhitom.wav",
    "001_brushlotom.wav",
    "002_brushsnare.wav",
    "003_brushsnareghost.wav",
    "004_closedhat.wav",
    "005_closedhathard.wav",
    "006_cowbell.wav",
    "007_cymbalgrab.wav",
    "008_cymbalrub.wav",
    "009_flam.wav",
    "010_foothat.wav",
    "011_foothat2.wav",
    "012_hitom.wav",
    "013_kick.wav",
    "014_kicksnare.wav",
    "015_lotom.wav",
    "016_openclosedhat.wav",
    "017_openhat.wav",
    "018_ridebell.wav",
    "019_ridecymbal.wav",
    "020_snare.wav",
    "021_snareghost.wav",
    "022_snarehard.wav",
    "023_snareslack.wav"
  },
  },
  ["gtr"] = {
    description = "three long C notes elect guitar",
    files = {
    "0001_cleanC.wav",
    "0002_ovrdC.wav",
    "0003_distC.wav"
  },
  },
  ["h"] = {
    description = "short baby sounds?",
    files = {
    "000_0_da0.wav",
    "001_0_da0-200%_1000_0_R.wav",
    "002_0_da0-50%_1000_0_R.wav",
    "003_1_da1.wav",
    "004_2_da2.wav",
    "005_3_tick.wav",
    "006_4_tock.wav"
  },
  },
  ["hand"] = {
    description = "mix of quiet clap sounds, some longer",
    files = {
    "hand1-mono.wav",
    "hand11-mono.wav",
    "hand12-mono.wav",
    "hand13-mono.wav",
    "hand14-mono.wav",
    "hand15-mono.wav",
    "hand16-mono.wav",
    "hand17.wav",
    "hand2-mono.wav",
    "hand20.wav",
    "hand21-mono.wav",
    "hand22-mono.wav",
    "hand3-mono.wav",
    "hand4-mono.wav",
    "hand7-mono.wav",
    "hand8-mono.wav",
    "hand9-mono.wav"
  },
  },
  ["hardcore"] = {
    description = "12 synth drum hits",
    files = {
    "000_hcclosedhh.wav",
    "001_hchit1.wav",
    "002_hccrash.wav",
    "003_hchit2.wav",
    "004_hckick1.wav",
    "005_hckick2.wav",
    "006_hcopenhh.wav",
    "007_hcperc1.wav",
    "008_hcperc2.wav",
    "009_hcride.wav",
    "010_hcsnare1.wav",
    "011_hcsnare2.wav"
  },
  },
  ["hardkick"] = {
    description = "6 rather loud crushed kicks",
    files = {
    "VEC1 BD Distortion 06.wav",
    "VEC1 BD Distortion 37.wav",
    "VEC1 BD Distortion 39.wav",
    "VEC1 BD Distortion 41.wav",
    "VEC1 BD Distortion 52.wav",
    "VEC1 BD Distortion 53.wav"
  },
  },
  ["haw"] = {
    description = "6 odd short hits",
    files = {
    "hawaiian-hh.wav",
    "hawaiian-kick.wav",
    "hawaiian-pop.wav",
    "hawaiian-sd.wav",
    "hawaiian-short1.wav",
    "hawaiian-short2.wav"
  },
  },
  ["hc"] = {
    description = "6 closed hats",
    files = {
    "HHCD0.wav",
    "HHCD2.wav",
    "HHCD4.wav",
    "HHCD6.wav",
    "HHCD8.wav",
    "HHCDA.wav"
  },
  },
  ["hh"] = {
    description = "actually a mix of drum sounds, quiet, ok",
    files = {
    "000_hh3closedhh.wav",
    "001_hh3crash.wav",
    "002_hh3hit1.wav",
    "003_hh3hit2.wav",
    "004_hh3hit3.wav",
    "005_hh3kick1.wav",
    "006_hh3kick2.wav",
    "007_hh3openhh.wav",
    "008_hh3rerc1.wav",
    "009_hh3rerc2.wav",
    "010_hh3ride.wav",
    "011_hh3snare1.wav",
    "012_hh3snare2.wav"
  },
  },
  ["hh27"] = {
    description = "another quiet set of electro drum hits",
    files = {
    "000_hh27closedhh.wav",
    "001_hh27crash.wav",
    "002_hh27hit1.wav",
    "003_hh27hit2.wav",
    "004_hh27hit3.wav",
    "005_hh27kick1.wav",
    "006_hh27kick2.wav",
    "007_hh27opendhh.wav",
    "008_hh27perc1.wav",
    "009_hh27perc2.wav",
    "010_hh27ride.wav",
    "011_hh27snare1.wav",
    "012_hh27snare2.wav"
  },
  },
  ["hit"] = {
    description = "strange hits, 04 one quite long",
    files = {
    "bandpass-blart.wav",
    "electro-pling1.wav",
    "laser-powered-sword.wav",
    "robot-fart.wav",
    "ufo-take-me-away.wav",
    "zap-to-crack.wav"
  },
  },
  ["hmm"] = {
    description = "female voice saying 'hmm'",
    files = {
    "hmm.wav"
  },
  },
  ["ho"] = {
    description = "six open hats, same but of varying length",
    files = {
    "HHOD0.wav",
    "HHOD2.wav",
    "HHOD4.wav",
    "HHOD6.wav",
    "HHOD8.wav",
    "HHODA.wav"
  },
  },
  ["hoover"] = {
    description = "six loud hoover bass soundss",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav"
  },
  },
  ["house"] = {
    description = "quite a nice kit, one pitched sound at 5 ~ Ebm",
    files = {
    "000_BD.wav",
    "001_CB.wav",
    "002_FX.wav",
    "003_HH.wav",
    "004_OH.wav",
    "005_P1.wav",
    "006_P2.wav",
    "007_SN.wav"
  },
  },
  ["ht"] = {
    description = "16 syn toms, rather similar",
    files = {
    "HT0D0.wav",
    "HT0D3.wav",
    "HT0D7.wav",
    "HT0DA.wav",
    "HT3D0.wav",
    "HT3D3.wav",
    "HT3D7.wav",
    "HT3DA.wav",
    "HT7D0.wav",
    "HT7D3.wav",
    "HT7D7.wav",
    "HT7DA.wav",
    "HTAD0.wav",
    "HTAD3.wav",
    "HTAD7.wav",
    "HTADA.wav"
  },
  },
  ["if"] = {
    description = "five bitcrushed hits",
    files = {
    "000_gab.wav",
    "001_gab2.wav",
    "002_snarl1b.wav",
    "003_snarl2b.wav",
    "004_snarl3b.wav"
  },
  },
  ["ifdrums"] = {
    description = "kick, hat, snare",
    files = {
    "ignorebd.wav",
    "ignorehh.wav",
    "ignoresd.wav"
  },
  },
  ["incoming"] = {
    description = "very electro kit, meh",
    files = {
    "000_Mattel  Snare.wav",
    "001_Mattel  Tom VHigh.wav",
    "002_Mattel Cymbal.wav",
    "003_Mattel Hi-Hat.wav",
    "004_Mattel Kick.wav",
    "005_Mattel Tom High.wav",
    "006_Mattel Tom Low.wav",
    "007_Mattel Tom VLow.wav"
  },
  },
  ["industrial"] = {
    description = "iya mix of metallic percussive sounds",
    files = {
    "000_01.wav",
    "001_02.wav",
    "002_03.wav",
    "003_04.wav",
    "004_05.wav",
    "005_06.wav",
    "006_07.wav",
    "007_08.wav",
    "008_09.wav",
    "009_10.wav",
    "010_11.wav",
    "011_12.wav",
    "012_13.wav",
    "013_14.wav",
    "014_15.wav",
    "015_16.wav",
    "016_17.wav",
    "017_18.wav",
    "018_19.wav",
    "019_20.wav",
    "020_21.wav",
    "021_22.wav",
    "022_23.wav",
    "023_24.wav",
    "024_25.wav",
    "025_26.wav",
    "026_27.wav",
    "027_28.wav",
    "028_29.wav",
    "029_30.wav",
    "030_31.wav",
    "031_32.wav"
  },
  },
  ["insect"] = {
    description = "three very quiet cricket sounds",
    files = {
    "000_everglades_conehead.wav",
    "001_robust_shieldback.wav",
    "002_seashore_meadow_katydid.wav"
  },
  },
  ["invaders"] = {
    description = "space invaders sounds, varied lengths",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_11.wav",
    "003_12.wav",
    "004_13.wav",
    "005_14.wav",
    "006_15.wav",
    "007_16.wav",
    "008_17.wav",
    "009_18.wav",
    "010_2.wav",
    "011_3.wav",
    "012_4.wav",
    "013_5.wav",
    "014_6.wav",
    "015_7.wav",
    "016_8.wav",
    "017_9.wav"
  },
  },
  ["jazz"] = {
    description = "totally not jazzy at all kit!",
    files = {
    "000_BD.wav",
    "001_CB.wav",
    "002_FX.wav",
    "003_HH.wav",
    "004_OH.wav",
    "005_P1.wav",
    "006_P2.wav",
    "007_SN.wav"
  },
  },
  ["jungbass"] = {
    description = "mostly longish sub-bass kind of sounds",
    files = {
    "000_deeep_n_low.wav",
    "001_fat_808_sub.wav",
    "002_fukubass2.wav",
    "003_glide_up_down_sub.wav",
    "004_gliding_808_sub.wav",
    "005_jungasubdown.wav",
    "006_junglerevbass.wav",
    "007_junglesine.wav",
    "008_junglesine2.wav",
    "009_junglesine3.wav",
    "010_mega_jungasubdown.wav",
    "011_shiphorn_tekstep_bass.wav",
    "012_short.wav",
    "013_sub_to_open_wah.wav",
    "014_sustained_2_octave.wav",
    "015_sustained_3_octave.wav",
    "016_sustained_deep_low.wav",
    "017_sweep_me_low_bass.wav",
    "018_synthy_round.wav",
    "019_thin_808_sub.wav"
  },
  },
  ["jungle"] = {
    description = "quiet 'jungle' kit, amen-ish",
    files = {
    "jungle4closedhh.wav",
    "jungle4crash.wav",
    "jungle4hit1.wav",
    "jungle4hit2.wav",
    "jungle4hit3.wav",
    "jungle4kick1.wav",
    "jungle4kick2.wav",
    "jungle4openhh.wav",
    "jungle4perc1.wav",
    "jungle4perc2.wav",
    "jungle4ride.wav",
    "jungle4snare1.wav",
    "jungle4snare2.wav"
  },
  },
  ["juno"] = {
    description = "lead/pad notes and chords, C/Cminor",
    files = {
    "00_juno_raw_low.wav",
    "01_juno_raw_mid.wav",
    "02_juno_raw_high.wav",
    "03_juno_chorus_low.wav",
    "04_juno_chorus_mid.wav",
    "05_juno_chorus_high.wav",
    "06_juno_release_low.wav",
    "07_juno_release_mid.wav",
    "08_juno_release_high.wav",
    "09_juno_pad_c_minor_filter.wav",
    "10_juno_pad_c_minor_no_filter.wav",
    "11_juno_pad_c_minor_noise.wav"
  },
  },
  ["jvbass"] = {
    description = "selection synth notes, black notes starting Gb",
    files = {
    "000_01.wav",
    "001_02.wav",
    "002_03.wav",
    "003_04.wav",
    "004_05.wav",
    "005_06.wav",
    "006_07.wav",
    "007_08.wav",
    "008_09.wav",
    "009_10.wav",
    "010_11.wav",
    "011_12.wav",
    "012_13.wav"
  },
  },
  ["kicklinn"] = {
    description = "wisott",
    files = {
    "Linn Kick 1.wav"
  },
  },
  ["koy"] = {
    description = "two koyaanisqatsi long samples, more or less sample",
    files = {
    "01_left.wav",
    "02_right.wav"
  },
  },
  ["kurt"] = {
    description = "vocal samples with telephone eq?",
    files = {
    "000_kurt01.wav",
    "001_kurt02.wav",
    "002_kurt03.wav",
    "003_kurt04.wav",
    "004_kurt05.wav",
    "005_kurt06.wav",
    "006_kurt07.wav"
  },
  },
  ["latibro"] = {
    description = "pentatonic selection of open 12th synth samples",
    files = {
    "000_Sound2.wav",
    "001_Sound3.wav",
    "002_Sound4.wav",
    "003_Sound5.wav",
    "004_Sound6.wav",
    "005_Sound7.wav",
    "006_Sound8.wav",
    "007_Sound9.wav"
  },
  },
  ["led"] = {
    description = "two and a bit sample of drums plus intro bleed",
    files = {
    "000_foo.wav"
  },
  },
  ["less"] = {
    description = "four fairly extreme drum sounds, kind of cool",
    files = {
    "bass2.wav",
    "hhxx.wav",
    "kicklesshuman.wav",
    "snare.wav"
  },
  },
  ["lighter"] = {
    description = "short quiet noisy hits high pitch meh",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav",
    "004_4.wav",
    "005_5.wav",
    "006_6.wav",
    "007_7.wav",
    "008_8.wav",
    "009_9.wav",
    "010_10.wav",
    "011_11.wav",
    "012_12.wav",
    "013_13.wav",
    "014_14.wav",
    "015_15.wav",
    "016_16.wav",
    "017_17.wav",
    "018_18.wav",
    "019_19.wav",
    "020_20.wav",
    "021_21.wav",
    "022_22.wav",
    "023_23.wav",
    "024_24.wav",
    "025_25.wav",
    "026_26.wav",
    "027_27.wav",
    "028_28.wav",
    "029_29.wav",
    "030_30.wav",
    "031_31.wav",
    "032_32.wav"
  },
  },
  ["linnhats"] = {
    description = "wisott",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav"
  },
  },
  ["lt"] = {
    description = "16 loud synth low toms",
    files = {
    "LT0D0.wav",
    "LT0D3.wav",
    "LT0D7.wav",
    "LT0DA.wav",
    "LT3D0.wav",
    "LT3D3.wav",
    "LT3D7.wav",
    "LT3DA.wav",
    "LT7D0.wav",
    "LT7D3.wav",
    "LT7D7.wav",
    "LT7DA.wav",
    "LTAD0.wav",
    "LTAD3.wav",
    "LTAD7.wav",
    "LTADA.wav"
  },
  },
  ["made"] = {
    description = "synthetic hits, not sure how to characterise!",
    files = {
    "0.wav",
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav"
  },
  },
  ["made2"] = {
    description = "very nasty bitcrushed long sound!",
    files = {
    "output.wav"
  },
  },
  ["mash"] = {
    description = "low synth tom sound and sort of glitch sound, why",
    files = {
    "0.wav",
    "1.wav"
  },
  },
  ["mash2"] = {
    description = "longish low syntom sounds",
    files = {
    "000_output.wav",
    "001_output2.wav",
    "002_output3.wav",
    "003_output4.wav"
  },
  },
  ["metal"] = {
    description = "a tiny high metal tink at 10 pitches",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav",
    "004_4.wav",
    "005_5.wav",
    "006_6.wav",
    "007_7.wav",
    "008_8.wav",
    "009_9.wav"
  },
  },
  ["miniyeah"] = {
    description = "very short glitchy sounds, better -24",
    files = {
    "000_Sound0.wav",
    "001_Sound11.wav",
    "002_Sound23.wav",
    "003_Sound36.wav"
  },
  },
  ["monsterb"] = {
    description = "no idea",
    files = {
    "000_jumpdown.wav",
    "001_laughter.wav",
    "002_tongue.wav",
    "003_warping.wav",
    "004_wolfman.wav",
    "005_zap.wav"
  },
  },
  ["moog"] = {
    description = "long low synth notes, various pitches",
    files = {
    "000_Mighty Moog C2.wav",
    "001_Mighty Moog C3.wav",
    "002_Mighty Moog C4.wav",
    "003_Mighty Moog G1.wav",
    "004_Mighty Moog G2.wav",
    "005_Mighty Moog G3.wav",
    "006_Mighty Moog G4.wav"
  },
  },
  ["mouth"] = {
    description = "iya short vocal sounds?",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_11.wav",
    "003_12.wav",
    "004_13.wav",
    "005_14.wav",
    "006_15.wav",
    "007_2.wav",
    "008_3.wav",
    "009_4.wav",
    "010_5.wav",
    "011_6.wav",
    "012_7.wav",
    "013_8.wav",
    "014_9.wav"
  },
  },
  ["mp3"] = {
    description = "harsh noise hits, horrible",
    files = {
    "000_mp30.wav",
    "001_mp31.wav",
    "002_mp32.wav",
    "003_mp33.wav"
  },
  },
  ["msg"] = {
    description = "subtle quiet hits",
    files = {
    "000_msg0.wav",
    "001_msg1.wav",
    "002_msg2.wav",
    "003_msg3.wav",
    "004_msg4.wav",
    "005_msg5.wav",
    "006_msg6.wav",
    "007_msg7.wav",
    "008_msg8.wav"
  },
  },
  ["mt"] = {
    description = "16 medium synth toms",
    files = {
    "MT0D0.wav",
    "MT0D3.wav",
    "MT0D7.wav",
    "MT0DA.wav",
    "MT3D0.wav",
    "MT3D3.wav",
    "MT3D7.wav",
    "MT3DA.wav",
    "MT7D0.wav",
    "MT7D3.wav",
    "MT7D7.wav",
    "MT7DA.wav",
    "MTAD0.wav",
    "MTAD3.wav",
    "MTAD7.wav",
    "MTADA.wav"
  },
  },
  ["mute"] = {
    description = "random collection of french horn notes and doubles",
    files = {
    "000_FH A#2 SCF.wav",
    "001_FH A3 SCF.wav",
    "002_FH B3 SCF.wav",
    "003_FH B4 SC.wav",
    "004_FH B4 SCF.wav",
    "005_FH C#3 SC.wav",
    "006_FH C#3 SCF.wav",
    "007_FH C#5 SCF.wav",
    "008_FH C4 SCF.wav",
    "009_FH D#4 SCF.wav",
    "010_FH D#5 SCF.wav",
    "011_FH D3 SC.wav",
    "012_FH D3 SCF.wav",
    "013_FH E3 SC.wav",
    "014_FH E3 SCF.wav",
    "015_FH F#4 SC.wav",
    "016_FH F#4 SCF.wav",
    "017_FH F3 SC.wav",
    "018_FH F3 SCF.wav",
    "019_FH F5 SCF.wav",
    "020_FH G#2 SC.wav",
    "021_FH G#2 SCF.wav",
    "022_FH G#3 SC.wav",
    "023_FH G#3 SCF.wav",
    "024_FH G#4 SC.wav",
    "025_FH G#4 SCF.wav",
    "026_FH G2 SC.wav",
    "027_FH G2 SCF.wav"
  },
  },
  ["newnotes"] = {
    description = "short high sine notes, black notes?",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_10.wav",
    "003_11.wav",
    "004_12.wav",
    "005_13.wav",
    "006_14.wav",
    "007_2.wav",
    "008_3.wav",
    "009_4.wav",
    "010_5.wav",
    "011_6.wav",
    "012_7.wav",
    "013_8.wav",
    "014_9.wav"
  },
  },
  ["noise"] = {
    description = "short quiet noise burst",
    files = {
    "000_noise.wav"
  },
  },
  ["noise2"] = {
    description = "8 short noise hits, three much louder than the others",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav",
    "004_4.wav",
    "005_5.wav",
    "006_6.wav",
    "007_7.wav"
  },
  },
  ["notes"] = {
    description = "same as newnotes, sines",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_10.wav",
    "003_11.wav",
    "004_12.wav",
    "005_13.wav",
    "006_14.wav",
    "007_2.wav",
    "008_3.wav",
    "009_4.wav",
    "010_5.wav",
    "011_6.wav",
    "012_7.wav",
    "013_8.wav",
    "014_9.wav"
  },
  },
  ["num"] = {
    description = "",
    files = {
    "00.wav",
    "01.wav",
    "02.wav",
    "03.wav",
    "04.wav",
    "05.wav",
    "06.wav",
    "07.wav",
    "08.wav",
    "09.wav",
    "10.wav",
    "11.wav",
    "12.wav",
    "13.wav",
    "14.wav",
    "15.wav",
    "16.wav",
    "17.wav",
    "18.wav",
    "19.wav",
    "20.wav"
  },
  },
  ["numbers"] = {
    description = "female voice individual numbers",
    files = {
    "0.wav",
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav",
    "7.wav",
    "8.wav"
  },
  },
  ["oc"] = {
    description = "open-closed hats in single hits at four tempi",
    files = {
    "OPCL1.wav",
    "OPCL2.wav",
    "OPCL3.wav",
    "OPCL4.wav"
  },
  },
  ["odx"] = {
    description = "fairly aggressive kit, not very nice, new order apparently",
    files = {
    "000_Kick_1.wav",
    "001_DX_Snare_1.wav",
    "002_DXShaker.wav",
    "003_DXRimshot.wav",
    "004_DXRide.wav",
    "005_DX_Open_Hat.wav",
    "006_DX_Mid_Tom.wav",
    "007_DX_Med_Crash.wav",
    "008_DX_Low_Tom.wav",
    "009_DX_Lo_Crash.wav",
    "010_DX_Hi_Tom.wav",
    "011_DX_High_Crash.wav",
    "012_DX_Cl_Hat.wav",
    "013_DXClap.wav",
    "014_DX_Ax_Hat.wav"
  },
  },
  ["off"] = {
    description = "single short glitchy bass note C#",
    files = {
    "000_01.wav"
  },
  },
  ["outdoor"] = {
    description = "odd ambient hits, 2 is quite long, interesting",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav",
    "5.wav",
    "6.wav"
  },
  },
  ["pad"] = {
    description = "four very assorted long sounds, not exactly pads",
    files = {
    "alien-monolith-pad.wav",
    "angelpads.wav",
    "bellpad-harmonics.wav"
  },
  },
  ["padlong"] = {
    description = "evolving m9 interval synth d2 $ s \"superpiano\" # up \"[a2,g4]\"",
    files = {
    "atmospheric-abduction.wav"
  },
  },
  ["pebbles"] = {
    description = "very long, maybe pebbles on a beach",
    files = {
    "90788__kmoon__pebbles-scrape-drag-foot.wav"
  },
  },
  ["perc"] = {
    description = "ok set of hits",
    files = {
    "000_perc0.wav",
    "001_perc1.wav",
    "002_perc2.wav",
    "003_perc3.wav",
    "004_perc4.wav",
    "005_perc5.wav"
  },
  },
  ["peri"] = {
    description = "collection of synth hits, ok",
    files = {
    "000_bd.wav",
    "001_bd-rev.wav",
    "002_hh2.wav",
    "003_hhx.wav",
    "004_ksh.wav",
    "005_sd.wav",
    "006_sd-rev.wav",
    "007_xbigclang.wav",
    "008_xbong.wav",
    "009_xbusket.wav",
    "010_xchinga.wav",
    "011_xfx1.wav",
    "012_xfx2.wav",
    "013_xfx3.wav",
    "014_xgillclank.wav"
  },
  },
  ["pluck"] = {
    description = "pizz cb notes various, 0 is B (ish)",
    files = {
    "BS A#2 PI.wav",
    "BS A1 PI.wav",
    "BS A3 PI.wav",
    "BS B1 PI.wav",
    "BS B3 PI.wav",
    "BS C3 PI.wav",
    "BS D#3 PI.wav",
    "BS D2 PI.wav",
    "BS D4 PI.wav",
    "BS E1 PI.wav",
    "BS E2 PI.wav",
    "BS F1 PI.wav",
    "BS F3 PI.wav",
    "BS G#2 PI.wav",
    "BS G1 PI.wav",
    "BS G2 PI.wav",
    "BS G3 PI.wav"
  },
  },
  ["popkick"] = {
    description = "kicks, but also tuned-ish in there",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_2.wav",
    "003_3.wav",
    "004_4.wav",
    "005_5.wav",
    "006_6.wav",
    "007_7.wav",
    "008_8.wav",
    "009_9.wav"
  },
  },
  ["print"] = {
    description = "dot matrix printer sounds, ok!",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_10.wav",
    "003_2.wav",
    "004_3.wav",
    "005_4.wav",
    "006_5.wav",
    "007_6.wav",
    "008_7.wav",
    "009_8.wav",
    "010_9.wav"
  },
  },
  ["proc"] = {
    description = "two computer glitch sounds?",
    files = {
    "000_2.wav",
    "001_3.wav"
  },
  },
  ["procshort"] = {
    description = "computer sounds edited very short, clicky",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_11.wav",
    "003_4.wav",
    "004_5.wav",
    "005_7.wav",
    "006_8.wav",
    "007_9.wav"
  },
  },
  ["psr"] = {
    description = "odd mix of ?game sounds mostly short 0 is a kalimba",
    files = {
    "000_01.wav",
    "001_02.wav",
    "002_03.wav",
    "003_04.wav",
    "004_05.wav",
    "005_06.wav",
    "006_07.wav",
    "007_08.wav",
    "008_09.wav",
    "009_10.wav",
    "010_11.wav",
    "011_12.wav",
    "012_13.wav",
    "013_14.wav",
    "014_15.wav",
    "015_16.wav",
    "016_17.wav",
    "017_18.wav",
    "018_19.wav",
    "019_20.wav",
    "020_21.wav",
    "021_22.wav",
    "022_23.wav",
    "023_24.wav",
    "024_25.wav",
    "025_26.wav",
    "026_27.wav",
    "027_28.wav",
    "028_29.wav",
    "029_30.wav"
  },
  },
  ["rave"] = {
    description = "soul shout vocals 'are you ready' etc",
    files = {
    "AREUREADY.wav",
    "Babylon.wav",
    "cut.wav",
    "doh.wav",
    "giveit.wav",
    "ourcrew.wav",
    "prodigyloop.wav",
    "stabah.wav"
  },
  },
  ["rave2"] = {
    description = "",
    files = {
    "rave_bass01.wav",
    "rave_bass02.wav",
    "rave_bass03.wav",
    "rave_bass04.wav"
  },
  },
  ["ravemono"] = {
    description = "mono versions of rave shouts",
    files = {
    "Babylon.wav",
    "prodigyloop.wav"
  },
  },
  ["realclaps"] = {
    description = "wisott",
    files = {
    "1.wav",
    "2.wav",
    "3.wav",
    "4.wav"
  },
  },
  ["reverbkick"] = {
    description = "wisott",
    files = {
    "1.wav"
  },
  },
  ["rm"] = {
    description = "two identical retro drum machine toms",
    files = {
    "RIM0.wav",
    "RIMA.wav"
  },
  },
  ["rs"] = {
    description = "retro drum machine metro sound?",
    files = {
    "rytm-rs.wav"
  },
  },
  ["sax"] = {
    description = "chromatic collection of very long bari notes",
    files = {
    "000_notes121a.wav",
    "001_notes121a2.wav",
    "002_notes121b.wav",
    "003_notes121bflat.wav",
    "004_notes121bflat2.wav",
    "005_notes121c.wav",
    "006_notes121c2.wav",
    "007_notes121csharp.wav",
    "008_notes121csharp2.wav",
    "009_notes121d.wav",
    "010_notes121e.wav",
    "011_notes121e2.wav",
    "012_notes121eflat.wav",
    "013_notes121eflat2.wav",
    "014_notes121f.wav",
    "015_notes121f2.wav",
    "016_notes121fsharp.wav",
    "017_notes121fsharp2.wav",
    "018_notes121g.wav",
    "019_notes121g2.wav",
    "020_notes121gsharp.wav",
    "021_notes121gsharp2.wav"
  },
  },
  ["sd"] = {
    description = "two very similar retro snares, not that great!",
    files = {
    "rytm-00-hard.wav",
    "rytm-01-classic.wav"
  },
  },
  ["seawolf"] = {
    description = "noise hits",
    files = {
    "000_minehit.wav",
    "001_shiphit.wav",
    "002_torpedo.wav"
  },
  },
  ["sequential"] = {
    description = "dry acoustic-ish kit",
    files = {
    "000_Tom Clap.wav",
    "001_Tom Crash.wav",
    "002_Tom Hat Closed.wav",
    "003_Tom Kick.wav",
    "004_Tom Openhat.wav",
    "005_Tom Snare.wav",
    "006_Tom Tom1.wav",
    "007_Tom Tom2.wav"
  },
  },
  ["sf"] = {
    description = "kind of interesting collection of short hits, one C note at 0",
    files = {
    "000_bass.wav",
    "001_1.wav",
    "002_10.wav",
    "003_11.wav",
    "004_12.wav",
    "005_13.wav",
    "006_14.wav",
    "007_15.wav",
    "008_16.wav",
    "009_17.wav",
    "010_2.wav",
    "011_3.wav",
    "012_4.wav",
    "013_5.wav",
    "014_6.wav",
    "015_7.wav",
    "016_8.wav",
    "017_9.wav"
  },
  },
  ["sheffield"] = {
    description = "long ambience",
    files = {
    "jakeinsects.wav"
  },
  },
  ["short"] = {
    description = "elctro kit sounds meh",
    files = {
    "sampleoftheday-gtt-fx-synth-009.wav",
    "sampleoftheday-gtt-snare-drum-010.wav",
    "sampleoftheday-gtt-snare-drum-012.wav",
    "sampleoftheday-gtt-snare-drum-020.wav",
    "sampleoftheday-gtt-snare-drum-021.wav"
  },
  },
  ["sid"] = {
    description = "ok, pretty usable sid sounds, melodic potential",
    files = {
    "000_bas2.wav",
    "001_bas.wav",
    "002_basd.wav",
    "003_blipp01.wav",
    "004_blipp02.wav",
    "005_high.wav",
    "006_high2.wav",
    "007_hihat01.wav",
    "008_hihat02.wav",
    "009_lofidrums.wav",
    "010_sidsnares.wav",
    "011_tdrum.wav"
  },
  },
  ["simplesine"] = {
    description = "",
    files = {
    "000_sine.wav",
    "001_sine2.wav",
    "002_sine3.wav",
    "003_sine4.wav",
    "004_sine5.wav",
    "005_sine6.wav"
  },
  },
  ["sitar"] = {
    description = "longish sitar gestures",
    files = {
    "000_d_maj_sitar_chorda.wav",
    "001_d_maj_sitar_chordb.wav",
    "002_d_maj_sitar_chordc.wav",
    "003_d_maj_sitar_chordd.wav",
    "004_d_maj_sitar_chorde.wav",
    "005_d_minor_sitar_chorda.wav",
    "006_d_minor_sitar_chordb.wav",
    "007_d_minor_sitar_chordc.wav"
  },
  },
  ["sn"] = {
    description = "",
    files = {
    "ST0T0S0.wav",
    "ST0T0S3.wav",
    "ST0T0S7.wav",
    "ST0T0SA.wav",
    "ST0T3S3.wav",
    "ST0T3S7.wav",
    "ST0T3SA.wav",
    "ST0T7S3.wav",
    "ST0T7S7.wav",
    "ST0T7SA.wav",
    "ST0TAS3.wav",
    "ST0TAS7.wav",
    "ST0TASA.wav",
    "ST3T0S0.wav",
    "ST3T0S3.wav",
    "ST3T0S7.wav",
    "ST3T0SA.wav",
    "ST3T3S3.wav",
    "ST3T3S7.wav",
    "ST3T3SA.wav",
    "ST3T7S3.wav",
    "ST3T7S7.wav",
    "ST3T7SA.wav",
    "ST3TAS3.wav",
    "ST3TAS7.wav",
    "ST3TASA.wav",
    "ST7T0S0.wav",
    "ST7T0S3.wav",
    "ST7T0S7.wav",
    "ST7T0SA.wav",
    "ST7T3S3.wav",
    "ST7T3S7.wav",
    "ST7T3SA.wav",
    "ST7T7S3.wav",
    "ST7T7S7.wav",
    "ST7T7SA.wav",
    "ST7TAS3.wav",
    "ST7TAS7.wav",
    "ST7TASA.wav",
    "STAT0S0.wav",
    "STAT0S3.wav",
    "STAT0S7.wav",
    "STAT0SA.wav",
    "STAT3S3.wav",
    "STAT3S7.wav",
    "STAT3SA.wav",
    "STAT7S3.wav",
    "STAT7S7.wav",
    "STAT7SA.wav",
    "STATAS3.wav",
    "STATAS7.wav",
    "STATASA.wav"
  },
  },
  ["space"] = {
    description = "strange mix of long/short sounds",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_11.wav",
    "003_12.wav",
    "004_13.wav",
    "005_14.wav",
    "006_15.wav",
    "007_16.wav",
    "008_17.wav",
    "009_18.wav",
    "010_2.wav",
    "011_3.wav",
    "012_4.wav",
    "013_5.wav",
    "014_6.wav",
    "015_7.wav",
    "016_8.wav",
    "017_9.wav"
  },
  },
  ["speakspell"] = {
    description = "short tts iya!",
    files = {
    "000_1.wav",
    "001_10.wav",
    "002_11.wav",
    "003_12.wav",
    "004_2.wav",
    "005_3.wav",
    "006_4.wav",
    "007_5.wav",
    "008_6.wav",
    "009_7.wav",
    "010_8.wav",
    "011_9.wav"
  },
  },
  ["speech"] = {
    description = "male vocal fragments plus two short hits",
    files = {
    "000_Sound10.wav",
    "001_Sound4.wav",
    "002_Sound5.wav",
    "003_Sound6.wav",
    "004_Sound7.wav",
    "005_Sound8.wav",
    "006_Sound9.wav"
  },
  },
  ["speechless"] = {
    description = "bits of male tts",
    files = {
    "000_a.wav",
    "001_pe.wav",
    "002_pepepe.wav",
    "003_pepepepepe.wav",
    "004_pepper.wav",
    "005_pepperpot.wav",
    "006_pick.wav",
    "007_pickle.wav",
    "008_po.wav",
    "009_te.wav"
  },
  },
  ["speedupdown"] = {
    description = "short fragments of sound inc one loud noise burst",
    files = {
    "000_Sound20.wav",
    "001_Sound21.wav",
    "002_Sound22.wav",
    "003_Sound23.wav",
    "004_Sound24.wav",
    "005_Sound25.wav",
    "006_Sound26.wav",
    "007_Sound27.wav",
    "008_Sound28.wav"
  },
  },
  ["stab"] = {
    description = "polysynth/fm hits, sort of pitched not really",
    files = {
    "000_stab1.wav",
    "001_stab10.wav",
    "002_stab11.wav",
    "003_stab12.wav",
    "004_stab13.wav",
    "005_stab14.wav",
    "006_stab15.wav",
    "007_stab16.wav",
    "008_stab17.wav",
    "009_stab18.wav",
    "010_stab19.wav",
    "011_stab2.wav",
    "012_stab20.wav",
    "013_stab21.wav",
    "014_stab22.wav",
    "015_stab23.wav",
    "016_stab3.wav",
    "017_stab4.wav",
    "018_stab5.wav",
    "019_stab6.wav",
    "020_stab7.wav",
    "021_stab8.wav",
    "022_stab9.wav"
  },
  },
  ["stomp"] = {
    description = "mostly kicks",
    files = {
    "000_0.wav",
    "001_0_2.wav",
    "002_1.wav",
    "003_2.wav",
    "004_3.wav",
    "005_5.wav",
    "006_6.wav",
    "007_7.wav",
    "008_8.wav",
    "009_9.wav"
  },
  },
  ["subroc3d"] = {
    description = "game sounds? some hits, one random melody",
    files = {
    "000_01.wav",
    "001_02.wav",
    "002_03.wav",
    "003_04.wav",
    "004_05.wav",
    "005_06.wav",
    "006_07.wav",
    "007_08.wav",
    "008_09.wav",
    "009_11.wav",
    "010_12.wav"
  },
  },
  ["sugar"] = {
    description = "",
    files = {
    "000_bark.wav",
    "001_crab.wav"
  },
  },
  ["sundance"] = {
    description = "very quiet beeps and an explosion, useless",
    files = {
    "000_bong.wav",
    "001_explsion.wav",
    "002_hatch.wav",
    "003_ping1.wav",
    "004_ping2.wav",
    "005_whoosh.wav"
  },
  },
  ["tabla"] = {
    description = "both hits and gestures",
    files = {
    "000_bass_flick1.wav",
    "001_bass_flick2.wav",
    "002_bass_lick1.wav",
    "003_dead_hit1.wav",
    "004_dead_hit2.wav",
    "005_dead_hit3.wav",
    "006_d_sharp_hit.wav",
    "007_hi_flick1.wav",
    "008_hi_flick2.wav",
    "009_hi_hit1.wav",
    "010_hi_hit10.wav",
    "011_hi_hit2.wav",
    "012_hi_hit3.wav",
    "013_hi_hit4.wav",
    "014_hi_hit5.wav",
    "015_hi_hit6.wav",
    "016_hi_hit7.wav",
    "017_hi_hit8.wav",
    "018_hi_hit9.wav",
    "019_lower1_hit.wav",
    "020_lower2_hit.wav",
    "021_lower3_hit.wav",
    "022_lower4_hit.wav",
    "023_lower5_hit.wav",
    "024_lower6_hit.wav",
    "025_lower_hits_descending.wav"
  },
  },
  ["tabla2"] = {
    description = "multisampled single hits",
    files = {
    "23645_loofa_A_001.wav",
    "23646_loofa_A_002.wav",
    "23647_loofa_A_003.wav",
    "23648_loofa_A_004.wav",
    "23649_loofa_A_005.wav",
    "23650_loofa_A_006.wav",
    "23651_loofa_A_007.wav",
    "23652_loofa_A_008.wav",
    "23653_loofa_A_009.wav",
    "23654_loofa_A_010.wav",
    "23655_loofa_A_011.wav",
    "23656_loofa_A_012.wav",
    "23657_loofa_A_013.wav",
    "23658_loofa_A_014.wav",
    "23659_loofa_A_015.wav",
    "23660_loofa_A_016.wav",
    "23661_loofa_A_017.wav",
    "23662_loofa_A_018.wav",
    "23663_loofa_A_019.wav",
    "23664_loofa_A_020.wav",
    "23665_loofa_A_021.wav",
    "23666_loofa_A_022.wav",
    "23667_loofa_A_023.wav",
    "23668_loofa_A_024.wav",
    "23669_loofa_A_025.wav",
    "23670_loofa_A_026.wav",
    "23671_loofa_A_027.wav",
    "23672_loofa_A_028.wav",
    "23673_loofa_bahia001.wav",
    "23674_loofa_bahia002.wav",
    "23675_loofa_bahia003.wav",
    "23676_loofa_bahia004.wav",
    "23677_loofa_bahia005.wav",
    "23678_loofa_bahia006.wav",
    "23679_loofa_bahia007.wav",
    "23680_loofa_bahia008.wav",
    "23681_loofa_bahia009.wav",
    "23682_loofa_bahia010.wav",
    "23683_loofa_bahia011.wav",
    "23684_loofa_bahia012.wav",
    "23685_loofa_bahia013.wav",
    "23686_loofa_bahia014.wav",
    "23687_loofa_bahia015.wav",
    "23688_loofa_bahia016.wav",
    "23689_loofa_bahia017.wav",
    "23690_loofa_bahia018.wav"
  },
  },
  ["tablex"] = {
    description = "male vocal fragments",
    files = {
    "0.wav",
    "1.wav",
    "fuckable.wav"
  },
  },
  ["tacscan"] = {
    description = "game sounds, some long",
    files = {
    "000_01.wav",
    "001_02.wav",
    "002_03.wav",
    "003_1up.wav",
    "004_credit.wav",
    "005_eexpl.wav",
    "006_eshot.wav",
    "007_flight1.wav",
    "008_flight2.wav",
    "009_flight3.wav",
    "010_flight4.wav",
    "011_flight5.wav",
    "012_formatn.wav",
    "013_pexpl.wav",
    "014_plaser.wav",
    "015_pship.wav",
    "016_sexpl.wav",
    "017_slaser.wav",
    "018_sthrust.wav",
    "019_tunnelh.wav",
    "020_tunnelw.wav",
    "021_warp.wav"
  },
  },
  ["tech"] = {
    description = "quiet but moderately interesting drum kit",
    files = {
    "tn1closedhh.wav",
    "tn1crash.wav",
    "tn1hit1.wav",
    "tn1hit2.wav",
    "tn1hit3.wav",
    "tn1kick1.wav",
    "tn1kick2.wav",
    "tn1openhh.wav",
    "tn1perc1.wav",
    "tn1perc2.wav",
    "tn1ride.wav",
    "tn1snare1.wav",
    "tn1snare2.wav"
  },
  },
  ["techno"] = {
    description = "hits, odd mix",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_3.wav",
    "003_4.wav",
    "004_5.wav",
    "005_6.wav",
    "006_7.wav"
  },
  },
  ["tink"] = {
    description = "high metallic sounds, pitched down iya",
    files = {
    "000_tink1.wav",
    "001_tink2.wav",
    "002_tink3.wav",
    "003_tink4.wav",
    "004_tink5.wav"
  },
  },
  ["tok"] = {
    description = "four kind of kick sounds",
    files = {
    "000_0.wav",
    "001_1.wav",
    "002_2.wav",
    "003_3.wav"
  },
  },
  ["toys"] = {
    description = "kids toy & voice 'classical music' and 'chimes'",
    files = {
    "000_ClassicalMusic.wav",
    "001_ClassicalMusic-Notes.wav",
    "002_ClassicalMusic-Words.wav",
    "003_Colors.wav",
    "004_Colors-Notes.wav",
    "005_Colors-Words.wav",
    "006_MusicalMedley.wav",
    "007_MusicalMedley-Notes.wav",
    "008_MusicalMedley-Words.wav",
    "009_Numbers.wav",
    "010_Numbers-Notes.wav",
    "011_Numbers-Words.wav",
    "012_ToyNotes.wav"
  },
  },
  ["trump"] = {
    description = "trumpet falls one phrase, thin eq",
    files = {
    "000_tightstabb.wav",
    "001_tightstabblowoct.wav",
    "002_tightstabe.wav",
    "003_tightstabg.wav",
    "004_trumpfunk107a.wav",
    "005_trumpstabb.wav",
    "006_trumpstabblowoct.wav",
    "007_trumpstabe.wav",
    "008_trumpstabg.wav",
    "009_trumpstabschord.wav",
    "010_trumptightstabschord.wav"
  },
  },
  ["ul"] = {
    description = "sort of hits/kit, some character, verby, loud",
    files = {
    "000_beep.wav",
    "001_little-whip.wav",
    "002_ulhh.wav",
    "003_ulkick.wav",
    "004_ulnoisey-kick.wav",
    "005_ulnoisey-run.wav",
    "006_ulnoisey-snare.wav",
    "007_ulsnare.wav",
    "008_ulsnare-reverb.wav",
    "009_ulsnare-reverse.wav"
  },
  },
  ["ulgab"] = {
    description = "short bitcrushed hits, usable",
    files = {
    "gab1.wav",
    "gab2.wav",
    "gab3.wav",
    "gab4.wav",
    "gab5.wav"
  },
  },
  ["uxay"] = {
    description = "one kick and two other sounds",
    files = {
    "000_bar.wav",
    "001_erk.wav",
    "002_foo.wav"
  },
  },
  ["v"] = {
    description = "6 mixed electronic sounds, kind of a kit",
    files = {
    "000_b_blipp01.wav",
    "001_v_blipp02.wav",
    "002_v_perc3.wav",
    "003_v_perc5.wav",
    "004_v_snare01.wav",
    "005_v_snare02.wav"
  },
  },
  ["voodoo"] = {
    description = "actually quite a nice five sound kit",
    files = {
    "000_VoodooBass.wav",
    "001_VoodooHihat.wav",
    "002_VoodooRim.wav",
    "003_VoodooSnare.wav",
    "004_VoodooTom.wav"
  },
  },
  ["wind"] = {
    description = "actually filtered white noise hits",
    files = {
    "000_wind1.wav",
    "001_wind10.wav",
    "002_wind2.wav",
    "003_wind3.wav",
    "004_wind4.wav",
    "005_wind5.wav",
    "006_wind6.wav",
    "007_wind7.wav",
    "008_wind8.wav",
    "009_wind9.wav"
  },
  },
  ["wobble"] = {
    description = "one subbass hit",
    files = {
    "000_0.wav"
  },
  },
  ["world"] = {
    description = "three kit hits, meh",
    files = {
    "bd.wav",
    "gabbakick.wav",
    "sn.wav"
  },
  },
  ["xmas"] = {
    description = "voice saying 'merry christmas'",
    files = {
    "170535__cognito-perceptu__merry-christmas.wav"
  },
  },
  ["yeah"] = {
    description = "big selection of short clicks and pops, usable",
    files = {
    "000_Sound0.wav",
    "001_Sound10.wav",
    "002_Sound11.wav",
    "003_Sound13.wav",
    "004_Sound14.wav",
    "005_Sound15.wav",
    "006_Sound17.wav",
    "007_Sound18.wav",
    "008_Sound19.wav",
    "009_Sound20.wav",
    "010_Sound21.wav",
    "011_Sound22.wav",
    "012_Sound23.wav",
    "013_Sound24.wav",
    "014_Sound25.wav",
    "015_Sound26.wav",
    "016_Sound27.wav",
    "017_Sound28.wav",
    "018_Sound29.wav",
    "019_Sound3.wav",
    "020_Sound32.wav",
    "021_Sound33.wav",
    "022_Sound34.wav",
    "023_Sound35.wav",
    "024_Sound36.wav",
    "025_Sound4.wav",
    "026_Sound5.wav",
    "027_Sound6.wav",
    "028_Sound7.wav",
    "029_Sound8.wav",
    "030_Sound9.wav"
  },
  },
}

function M.get_banks()
  local result = {}
  for name, info in pairs(M.banks) do
    table.insert(result, {
      name = name,
      description = info.description,
      file_count = #info.files,
    })
  end
  table.sort(result, function(a, b) return a.name < b.name end)
  return result
end

function M.get_files(name)
  local bank = M.banks[name]
  if not bank then
    return {}
  end
  return bank.files
end

return M
