#!/usr/bin/env lua
-- Script to regenerate lua/tidal/data/sample_banks.lua
-- Fetches bank names and file listings from tidalcycles/Dirt-Samples GitHub repo
-- and parses descriptions from allthesamples.tidal
--
-- Usage: lua scripts/update_sample_data.lua
-- Requires: curl, jq

local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function shell(cmd)
  local handle = io.popen(cmd)
  local result = handle:read("*a")
  handle:close()
  return result
end

-- Fetch bank directories from Dirt-Samples
print("Fetching bank list from Dirt-Samples...")
local banks_json = shell("curl -s https://api.github.com/repos/tidalcycles/Dirt-Samples/contents/")
local bank_names = {}
for name in banks_json:gmatch('"name"%s*:%s*"([^"]+)"') do
  bank_names[name] = true
end

-- Fetch allthesamples.tidal for descriptions
print("Fetching descriptions from allthesamples.tidal...")
local allsamples = shell("curl -s https://raw.githubusercontent.com/tedthetrumpet/tidal/master/allthesamples.tidal")

-- Parse descriptions: extract s "bankname" and trailing comments
local descriptions = {}
for line in allsamples:gmatch("[^\r\n]+") do
  if line:match('$ s "') then
    local bank = line:match('$ s "([^"]+)"')
    local desc = line:match("%-%-%s*(.+)$")
    if bank and desc then
      -- Handle bank!N format (e.g., "909!4")
      bank = bank:gsub("!.*$", "")
      descriptions[bank] = trim(desc)
    end
  end
end

-- Also parse lines with d1 $ s "bank" (without the $ before s)
for line in allsamples:gmatch("[^\r\n]+") do
  local bank, desc
  if line:match('^d%d+ $ s "') or line:match('^d%d+ .- $ s "') then
    bank = line:match('$ s "([^"]+)"')
    desc = line:match("%-%-%s*(.+)$")
  end
  -- Also direct form: d1 "noise" -- desc
  if not bank then
    bank = line:match('^d%d+%s+"([^"]+)"')
    desc = line:match("%-%-%s*(.+)$")
  end
  if bank and desc then
    bank = bank:gsub("!.*$", "")
    if not descriptions[bank] then
      descriptions[bank] = trim(desc)
    end
  end
end

-- Fetch file listings for each bank
print("Fetching file listings for each bank...")
local bank_files = {}
local count = 0
local total = 0
for name, _ in pairs(bank_names) do
  total = total + 1
end

for name, _ in pairs(bank_names) do
  count = count + 1
  io.write(string.format("\r[%d/%d] %-30s", count, total, name))
  io.flush()

  local files_json = shell(string.format(
    'curl -s --connect-timeout 5 "https://api.github.com/repos/tidalcycles/Dirt-Samples/contents/%s"',
    name
  ))

  local files = {}
  for fname in files_json:gmatch('"name"%s*:%s*"([^"]+)"') do
    if fname:match("%.wav$") or fname:match("%.WAV$") or fname:match("%.aif$") or fname:match("%.aiff$") then
      table.insert(files, fname)
    end
  end

  if #files > 0 then
    table.sort(files)
    bank_files[name] = files
  end

  -- Small delay to avoid rate limiting
  if count % 10 == 0 then
    os.execute("sleep 1")
  end
end
print("\nDone fetching files.")

-- Generate output
print("Generating sample_banks.lua...")
local out = [=[-- Bundled sample bank data from Dirt-Samples
-- Auto-generated by scripts/update_sample_data.lua
-- Descriptions from https://github.com/tedthetrumpet/tidal/blob/master/allthesamples.tidal
-- File listings from https://github.com/tidalcycles/Dirt-Samples

local M = {}

M.banks = {
]=]

-- Sort bank names for consistent output
local sorted_names = {}
for name, _ in pairs(bank_names) do
  table.insert(sorted_names, name)
end
table.sort(sorted_names)

for _, name in ipairs(sorted_names) do
  local desc = descriptions[name] or ""
  local files = bank_files[name] or {}
  local files_str
  if #files > 0 then
    local parts = {}
    for _, f in ipairs(files) do
      table.insert(parts, string.format("    %q", f))
    end
    files_str = "{\n" .. table.concat(parts, ",\n") .. "\n  }"
  else
    files_str = "{}"
  end
  out = out .. string.format("  [%q] = {\n    description = %q,\n    files = %s,\n  },\n", name, desc, files_str)
end

out = out .. [=[
}

function M.get_banks()
  local result = {}
  for name, info in pairs(M.banks) do
    table.insert(result, {
      name = name,
      description = info.description,
      file_count = #info.files,
    })
  end
  table.sort(result, function(a, b) return a.name < b.name end)
  return result
end

function M.get_files(name)
  local bank = M.banks[name]
  if not bank then
    return {}
  end
  return bank.files
end

return M
]=]

local f = io.open("lua/tidal/data/sample_banks.lua", "w")
if f then
  f:write(out)
  f:close()
  print("Wrote lua/tidal/data/sample_banks.lua")
else
  print("ERROR: Could not write file")
end
