#!/usr/bin/env lua
-- Script to regenerate lua/tidal/data/sample_banks.lua
-- Fetches the full Dirt-Samples file tree via the git trees API (single
-- request, no per-bank rate limiting) and parses descriptions from
-- allthesamples.tidal
--
-- Usage: lua scripts/update_sample_data.lua
-- Requires: curl

local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function shell(cmd)
  local handle = io.popen(cmd)
  local result = handle:read("*a")
  handle:close()
  return result
end

-- Fetch allthesamples.tidal for descriptions
print("Fetching descriptions from allthesamples.tidal...")
local allsamples = shell("curl -s https://raw.githubusercontent.com/tedthetrumpet/tidal/master/allthesamples.tidal")

-- Parse descriptions: extract s "bankname" and trailing comments
local descriptions = {}
local function record(banks, desc)
  if not banks or not desc then
    return
  end
  -- A line may reference several banks at once (e.g. s "alex:1 alex:2");
  -- map each token to its base bank, stripping !N and :N suffixes.
  for token in banks:gmatch("%S+") do
    local base = token:gsub("[!:]%d+.*$", "")
    if not descriptions[base] then
      descriptions[base] = trim(desc)
    end
  end
end
for line in allsamples:gmatch("[^\r\n]+") do
  if not line:match("^%s*%-%-") then
    record(line:match('s%s+"([^"]+)"'), line:match("%-%-%s*(.+)$"))
    -- Also the direct form: d1 "bank" -- desc
    record(line:match('^d%d+%s+"([^"]+)"'), line:match("%-%-%s*(.+)$"))
  end
end

-- Fetch full file tree from Dirt-Samples
print("Fetching Dirt-Samples tree...")
local tree_json = shell("curl -s --connect-timeout 10 https://api.github.com/repos/tidalcycles/Dirt-Samples/git/trees/main?recursive=1")

local bank_files = {}
local bank_names = {}
for path in tree_json:gmatch('"path"%s*:%s*"([^"]+)"') do
  local bank, fname = path:match("^([^/]+)/([^/]+)$")
  if bank and fname then
    bank_names[bank] = true
    if fname:match("%.wav$") or fname:match("%.WAV$") or fname:match("%.aif$") or fname:match("%.aiff$") or fname:match("%.AIFF$") then
      if not bank_files[bank] then
        bank_files[bank] = {}
      end
      table.insert(bank_files[bank], fname)
    end
  end
end
local bank_count = 0
for _ in pairs(bank_names) do
  bank_count = bank_count + 1
end
print("Fetched Dirt-Samples tree: " .. bank_count .. " banks, " .. tree_json:len() .. " bytes of tree data.")
print("Done fetching files.")

-- Generate output
print("Generating sample_banks.lua...")
local out = [=[-- Bundled sample bank data from Dirt-Samples
-- Auto-generated by scripts/update_sample_data.lua
-- Descriptions from https://github.com/tedthetrumpet/tidal/blob/master/allthesamples.tidal
-- File listings from https://github.com/tidalcycles/Dirt-Samples

local M = {}

M.banks = {
]=]

-- Sort bank names for consistent output
local sorted_names = {}
for name, _ in pairs(bank_names) do
  table.insert(sorted_names, name)
end
table.sort(sorted_names)

for _, name in ipairs(sorted_names) do
  local desc = descriptions[name] or ""
  local files = bank_files[name] or {}
  table.sort(files)
  local files_str
  if #files > 0 then
    local parts = {}
    for _, f in ipairs(files) do
      table.insert(parts, string.format("    %q", f))
    end
    files_str = "{\n" .. table.concat(parts, ",\n") .. "\n  }"
  else
    files_str = "{}"
  end
  out = out .. string.format("  [%q] = {\n    description = %q,\n    files = %s,\n  },\n", name, desc, files_str)
end

out = out .. [=[
}

function M.get_banks()
  local result = {}
  for name, info in pairs(M.banks) do
    table.insert(result, {
      name = name,
      description = info.description,
      file_count = #info.files,
    })
  end
  table.sort(result, function(a, b) return a.name < b.name end)
  return result
end

function M.get_files(name)
  local bank = M.banks[name]
  if not bank then
    return {}
  end
  return bank.files
end

return M
]=]

local f = io.open("lua/tidal/data/sample_banks.lua", "w")
if f then
  f:write(out)
  f:close()
  print("Wrote lua/tidal/data/sample_banks.lua")
else
  print("ERROR: Could not write file")
end
